-- Insert dummy profiles for testing
INSERT INTO users (
  id,
  email,
  first_name,
  last_name,
  gender,
  birthdate,
  city,
  state,
  country,
  mother_tongue,
  education,
  profession,
  diet,
  height,
  marital_status,
  family_type,
  family_values,
  caste,
  gotra,
  smoking,
  drinking,
  exercise_frequency,
  sleep_schedule,
  meditation_frequency,
  yoga_frequency,
  scripture_study,
  pilgrimage_interest,
  vanaprastha_interest,
  artha_vs_moksha,
  temple_visit_freq,
  about_me,
  partner_expectations,
  favorite_quote,
  quote_author,
  spiritual_org,
  daily_practices,
  favorite_scriptures,
  spiritual_goals,
  interests,
  hobbies,
  user_photos,
  verification_status,
  account_status,
  onboarding_completed,
  partner_age_min,
  partner_age_max,
  created_at
) VALUES 
-- Profile 1: Priya Sharma
(
  'dummy-user-1',
  'priya.sharma@example.com',
  'Priya',
  'Sharma',
  'Female',
  '1995-03-15',
  'Mumbai',
  'Maharashtra',
  'India',
  'Hindi',
  'Masters in Computer Science',
  'Software Engineer',
  'Vegetarian',
  '5''4"',
  'Never Married',
  'Nuclear',
  'Traditional',
  'Brahmin',
  'Bharadwaj',
  'Never',
  'Never',
  'Daily',
  'Early Bird (6-10 PM)',
  'Daily',
  'Daily',
  'Weekly',
  'Very Interested',
  'Interested',
  'Balanced',
  'Weekly',
  'I am a spiritual seeker who believes in the power of meditation and yoga. I work as a software engineer but my true passion lies in understanding the deeper meanings of life through ancient scriptures. I love spending time in nature and believe that a life partner should be someone who shares similar spiritual values and is committed to personal growth.',
  'Looking for someone who is spiritually inclined, values family traditions, and believes in growing together on the spiritual path. Education and profession are important, but character and spiritual maturity matter more to me.',
  'The mind is everything. What you think you become.',
  'Buddha',
  ARRAY['ISKCON', 'Art of Living'],
  ARRAY['Meditation', 'Yoga', 'Chanting', 'Scripture Reading'],
  ARRAY['Bhagavad Gita', 'Ramayana', 'Upanishads'],
  ARRAY['Self-realization', 'Service to humanity', 'Inner peace'],
  ARRAY['Reading', 'Classical Music', 'Cooking', 'Gardening'],
  ARRAY['Photography', 'Hiking', 'Painting'],
  ARRAY['/abstract-spiritual-avatar-1.png', '/abstract-spiritual-avatar-2.png'],
  'verified',
  'sangam',
  true,
  26,
  32,
  NOW() - INTERVAL '2 days'
),

-- Profile 2: Arjun Patel
(
  'dummy-user-2',
  'arjun.patel@example.com',
  'Arjun',
  'Patel',
  'Male',
  '1992-07-22',
  'Ahmedabad',
  'Gujarat',
  'India',
  'Gujarati',
  'MBA Finance',
  'Investment Banker',
  'Vegetarian',
  '5''10"',
  'Never Married',
  'Joint',
  'Traditional',
  'Patel',
  'Kashyap',
  'Never',
  'Occasionally',
  '4-5 times a week',
  'Night Owl (11 PM - 1 AM)',
  '3-4 times a week',
  'Daily',
  'Daily',
  'Very Interested',
  'Very Interested',
  'Moksha-focused',
  'Daily',
  'I come from a traditional Gujarati family and deeply value our cultural heritage. My spiritual journey began during college when I started reading the Bhagavad Gita. I believe in karma yoga - performing duties without attachment to results. I enjoy discussing philosophy and spirituality, and I am looking for a life partner who shares these interests.',
  'Seeking a partner who values spirituality, family traditions, and has a strong moral compass. Someone who can be my companion in both worldly responsibilities and spiritual growth.',
  'You have the right to perform your actions, but you are not entitled to the fruits of action.',
  'Bhagavad Gita',
  ARRAY['Swaminarayan Temple', 'Brahma Kumaris'],
  ARRAY['Meditation', 'Pranayama', 'Satsang', 'Seva'],
  ARRAY['Bhagavad Gita', 'Srimad Bhagavatam', 'Yoga Vasistha'],
  ARRAY['Moksha', 'Dharmic living', 'Family harmony'],
  ARRAY['Philosophy', 'Classical Music', 'Travel', 'Finance'],
  ARRAY['Chess', 'Cricket', 'Reading'],
  ARRAY['/abstract-spiritual-avatar-3.png', '/abstract-spiritual-avatar-4.png'],
  'verified',
  'samarpan',
  true,
  24,
  30,
  NOW() - INTERVAL '1 day'
),

-- Profile 3: Kavya Iyer
(
  'dummy-user-3',
  'kavya.iyer@example.com',
  'Kavya',
  'Iyer',
  'Female',
  '1994-11-08',
  'Chennai',
  'Tamil Nadu',
  'India',
  'Tamil',
  'Masters in Psychology',
  'Clinical Psychologist',
  'Vegetarian',
  '5''3"',
  'Never Married',
  'Nuclear',
  'Modern',
  'Iyer',
  'Bharadwaj',
  'Never',
  'Never',
  'Daily',
  'Early Bird (6-10 PM)',
  'Daily',
  'Daily',
  'Weekly',
  'Interested',
  'Somewhat Interested',
  'Balanced',
  'Weekly',
  'As a psychologist, I understand the importance of mental and spiritual well-being. I practice meditation and yoga daily, and I believe in the healing power of ancient Indian wisdom. I love classical dance and music, and I am passionate about helping others through my profession. I seek a partner who values both modern thinking and traditional wisdom.',
  'Looking for an educated, understanding partner who respects both tradition and modernity. Someone who values mental health, spirituality, and believes in equality in relationships.',
  'The greatest revolution of our generation is the discovery that human beings, by changing the inner attitudes of their minds, can change the outer aspects of their lives.',
  'William James',
  ARRAY['Isha Foundation', 'Ramakrishna Mission'],
  ARRAY['Meditation', 'Bharatanatyam', 'Yoga', 'Chanting'],
  ARRAY['Thirukkural', 'Bhagavad Gita', 'Vivekachudamani'],
  ARRAY['Inner peace', 'Helping others', 'Cultural preservation'],
  ARRAY['Classical Dance', 'Psychology', 'Music', 'Literature'],
  ARRAY['Dancing', 'Singing', 'Writing'],
  ARRAY['/abstract-spiritual-avatar-1.png', '/abstract-spiritual-avatar-3.png'],
  'verified',
  'sparsh',
  true,
  25,
  31,
  NOW() - INTERVAL '3 days'
),

-- Profile 4: Rohit Gupta
(
  'dummy-user-4',
  'rohit.gupta@example.com',
  'Rohit',
  'Gupta',
  'Male',
  '1990-12-03',
  'Delhi',
  'Delhi',
  'India',
  'Hindi',
  'B.Tech Mechanical Engineering',
  'Entrepreneur',
  'Vegetarian',
  '5''8"',
  'Never Married',
  'Joint',
  'Traditional',
  'Agarwal',
  'Garg',
  'Never',
  'Socially',
  '5-6 times a week',
  'Moderate (10-11 PM)',
  'Weekly',
  '3-4 times a week',
  'Monthly',
  'Somewhat Interested',
  'Interested',
  'Artha-focused',
  'Monthly',
  'I am an entrepreneur who believes in creating value while staying true to dharmic principles. Though I am focused on building my business, I never forget the importance of spirituality in life. I enjoy reading about successful people who have balanced material success with spiritual growth. I am looking for a partner who can support my ambitions while keeping me grounded in our values.',
  'Seeking an ambitious yet grounded partner who understands the balance between material success and spiritual values. Someone who can be my equal partner in all aspects of life.',
  'Success is not just about what you accomplish in your life, it''s about what you inspire others to do.',
  'Unknown',
  ARRAY['Arya Samaj'],
  ARRAY['Morning Prayer', 'Yoga', 'Reading'],
  ARRAY['Bhagavad Gita', 'Chanakya Niti'],
  ARRAY['Success with values', 'Family prosperity', 'Social contribution'],
  ARRAY['Business', 'Technology', 'Sports', 'Travel'],
  ARRAY['Cricket', 'Badminton', 'Reading'],
  ARRAY['/abstract-spiritual-avatar-2.png', '/abstract-spiritual-avatar-4.png'],
  'verified',
  'drishti',
  true,
  23,
  29,
  NOW() - INTERVAL '4 days'
),

-- Profile 5: Ananya Reddy
(
  'dummy-user-5',
  'ananya.reddy@example.com',
  'Ananya',
  'Reddy',
  'Female',
  '1996-05-18',
  'Hyderabad',
  'Telangana',
  'India',
  'Telugu',
  'Masters in Biotechnology',
  'Research Scientist',
  'Vegetarian',
  '5''5"',
  'Never Married',
  'Nuclear',
  'Progressive',
  'Reddy',
  'Kashyap',
  'Never',
  'Never',
  'Daily',
  'Early Bird (6-10 PM)',
  'Daily',
  'Daily',
  'Daily',
  'Very Interested',
  'Very Interested',
  'Moksha-focused',
  'Daily',
  'I am a research scientist who finds spirituality in the wonders of creation. Every day in the lab reminds me of the divine intelligence behind life. I practice meditation and study scriptures to understand the deeper purpose of existence. I believe science and spirituality complement each other beautifully. I am looking for someone who appreciates both the material and spiritual dimensions of life.',
  'Looking for an intellectually curious partner who can appreciate both scientific thinking and spiritual wisdom. Someone who is committed to personal growth and making a positive impact on the world.',
  'The more I study science, the more I believe in God.',
  'Albert Einstein',
  ARRAY['Brahma Kumaris', 'Satsang Foundation'],
  ARRAY['Meditation', 'Yoga', 'Satsang', 'Nature walks'],
  ARRAY['Bhagavad Gita', 'Yoga Sutras', 'Upanishads'],
  ARRAY['Self-realization', 'Scientific contribution', 'World peace'],
  ARRAY['Science', 'Spirituality', 'Nature', 'Research'],
  ARRAY['Microscopy', 'Gardening', 'Stargazing'],
  ARRAY['/abstract-spiritual-avatar-1.png', '/abstract-spiritual-avatar-4.png'],
  'verified',
  'sangam',
  true,
  25,
  32,
  NOW() - INTERVAL '5 days'
);
